import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assets = ["image/bootstrap.sh", "image/start.sh", "image/Containerfile"];
const values = [];
const digest = createHash("sha256");

for (const path of assets) {
  const content = await readFile(resolve(packageRoot, path), "utf8");
  digest.update(path).update("\0").update(content).update("\0");
  values.push({ path, content });
}

const output = [
  "// Generated by scripts/generate-assets.mjs. Do not edit.",
  ...values.map(({ path, content }) => `export const ${path.split("/").at(-1).replace(/[^a-zA-Z0-9]/g, "_")} = ${JSON.stringify(content)};`),
  `export const computerImageAssetDigest = "sha256:${digest.digest("hex")}";`,
  "",
].join("\n");

await mkdir(resolve(packageRoot, "src"), { recursive: true });
await writeFile(resolve(packageRoot, "src/generated-assets.ts"), output);
